
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class WidgetPocetna
	{
		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox7;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Image image1;

		private global::Gtk.Label label4;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Image image2;

		private global::Gtk.Label label5;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Image image3;

		private global::Gtk.Label label6;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Image image4;

		private global::Gtk.Label label7;

		private global::Gtk.HBox hbox8;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Image image5;

		private global::Gtk.Label label8;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Image image6;

		private global::Gtk.Label label9;

		private global::Gtk.VBox vbox12;

		private global::Gtk.Image image7;

		private global::Gtk.Label label10;

		private global::Gtk.VBox vbox13;

		private global::Gtk.Image image8;

		private global::Gtk.Label label11;

		private global::Gtk.HBox hbox9;

		private global::Gtk.VBox vbox14;

		private global::Gtk.Image image9;

		private global::Gtk.Label label12;

		private global::Gtk.VBox vbox15;

		private global::Gtk.Image image10;

		private global::Gtk.Label label13;

		private global::Gtk.VBox vbox16;

		private global::Gtk.Image image11;

		private global::Gtk.Label label14;

		private global::Gtk.VBox vbox17;

		private global::Gtk.Image image12;

		private global::Gtk.Label label15;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.WidgetPocetna
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ProjektProgramsko.WidgetPocetna";
			// Container child ProjektProgramsko.WidgetPocetna.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image();
			this.image1.WidthRequest = 70;
			this.image1.HeightRequest = 100;
			this.image1.Name = "image1";
			this.vbox6.Add(this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox6.Add(this.label4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label4]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox7.Add(this.vbox6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image();
			this.image2.WidthRequest = 70;
			this.image2.HeightRequest = 100;
			this.image2.Name = "image2";
			this.vbox7.Add(this.image2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.image2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox7.Add(this.label5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label5]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox7.Add(this.vbox7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox7]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.image3 = new global::Gtk.Image();
			this.image3.WidthRequest = 70;
			this.image3.HeightRequest = 100;
			this.image3.Name = "image3";
			this.vbox8.Add(this.image3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.image3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox8.Add(this.label6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label6]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox7.Add(this.vbox8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox8]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.image4 = new global::Gtk.Image();
			this.image4.WidthRequest = 70;
			this.image4.HeightRequest = 100;
			this.image4.Name = "image4";
			this.vbox9.Add(this.image4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.image4]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox9.Add(this.label7);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label7]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox7.Add(this.vbox9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox9]));
			w12.PackType = ((global::Gtk.PackType)(1));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image();
			this.image5.WidthRequest = 70;
			this.image5.HeightRequest = 100;
			this.image5.Name = "image5";
			this.vbox10.Add(this.image5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.image5]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox10.Add(this.label8);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label8]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox8.Add(this.vbox10);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.vbox10]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.image6 = new global::Gtk.Image();
			this.image6.WidthRequest = 70;
			this.image6.HeightRequest = 100;
			this.image6.Name = "image6";
			this.vbox11.Add(this.image6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.image6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox11.Add(this.label9);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label9]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox8.Add(this.vbox11);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.vbox11]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.image7 = new global::Gtk.Image();
			this.image7.WidthRequest = 70;
			this.image7.HeightRequest = 100;
			this.image7.Name = "image7";
			this.vbox12.Add(this.image7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.image7]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox12.Add(this.label10);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.label10]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox8.Add(this.vbox12);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.vbox12]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.image8 = new global::Gtk.Image();
			this.image8.WidthRequest = 70;
			this.image8.HeightRequest = 100;
			this.image8.Name = "image8";
			this.vbox13.Add(this.image8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.image8]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox13.Add(this.label11);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.label11]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox8.Add(this.vbox13);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.vbox13]));
			w25.PackType = ((global::Gtk.PackType)(1));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox5.Add(this.hbox8);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox8]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.image9 = new global::Gtk.Image();
			this.image9.WidthRequest = 70;
			this.image9.HeightRequest = 100;
			this.image9.Name = "image9";
			this.vbox14.Add(this.image9);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.image9]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox14.Add(this.label12);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.label12]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.hbox9.Add(this.vbox14);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox14]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.image10 = new global::Gtk.Image();
			this.image10.WidthRequest = 70;
			this.image10.HeightRequest = 100;
			this.image10.Name = "image10";
			this.vbox15.Add(this.image10);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.image10]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox15.Add(this.label13);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.label13]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.hbox9.Add(this.vbox15);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox15]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.image11 = new global::Gtk.Image();
			this.image11.WidthRequest = 70;
			this.image11.HeightRequest = 100;
			this.image11.Name = "image11";
			this.vbox16.Add(this.image11);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.image11]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox16.Add(this.label14);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label14]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.hbox9.Add(this.vbox16);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox16]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.image12 = new global::Gtk.Image();
			this.image12.WidthRequest = 70;
			this.image12.HeightRequest = 100;
			this.image12.Name = "image12";
			this.vbox17.Add(this.image12);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.image12]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.vbox17.Add(this.label15);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.label15]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			this.hbox9.Add(this.vbox17);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox17]));
			w38.PackType = ((global::Gtk.PackType)(1));
			w38.Position = 3;
			w38.Expand = false;
			w38.Fill = false;
			this.vbox5.Add(this.hbox9);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.Add(this.vbox5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
