
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class WidgetUredivanjeSadrzaja
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.RadioButton radiobuttonKnjiga;

		private global::Gtk.RadioButton radiobuttonCasopis;

		private global::Gtk.RadioButton radiobuttonFilm;

		private global::Gtk.RadioButton radiobuttonIzdanje;

		private global::Gtk.RadioButton radiobuttonAutori;

		private global::Gtk.VBox vbox2;

		private global::ProjektProgramsko.WidgetUredivanjeKnjiga widgeturedivanjeknjiga1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.WidgetUredivanjeSadrzaja
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ProjektProgramsko.WidgetUredivanjeSadrzaja";
			// Container child ProjektProgramsko.WidgetUredivanjeSadrzaja.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radiobuttonKnjiga = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Knjiga"));
			this.radiobuttonKnjiga.CanFocus = true;
			this.radiobuttonKnjiga.Name = "radiobuttonKnjiga";
			this.radiobuttonKnjiga.DrawIndicator = true;
			this.radiobuttonKnjiga.UseUnderline = true;
			this.radiobuttonKnjiga.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox1.Add(this.radiobuttonKnjiga);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonKnjiga]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radiobuttonCasopis = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Časopis"));
			this.radiobuttonCasopis.CanFocus = true;
			this.radiobuttonCasopis.Name = "radiobuttonCasopis";
			this.radiobuttonCasopis.DrawIndicator = true;
			this.radiobuttonCasopis.UseUnderline = true;
			this.radiobuttonCasopis.Group = this.radiobuttonKnjiga.Group;
			this.hbox1.Add(this.radiobuttonCasopis);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonCasopis]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radiobuttonFilm = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Film"));
			this.radiobuttonFilm.CanFocus = true;
			this.radiobuttonFilm.Name = "radiobuttonFilm";
			this.radiobuttonFilm.DrawIndicator = true;
			this.radiobuttonFilm.UseUnderline = true;
			this.radiobuttonFilm.Group = this.radiobuttonKnjiga.Group;
			this.hbox1.Add(this.radiobuttonFilm);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonFilm]));
			w3.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radiobuttonIzdanje = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Izdanje Časopis"));
			this.radiobuttonIzdanje.CanFocus = true;
			this.radiobuttonIzdanje.Name = "radiobuttonIzdanje";
			this.radiobuttonIzdanje.DrawIndicator = true;
			this.radiobuttonIzdanje.UseUnderline = true;
			this.radiobuttonIzdanje.Group = this.radiobuttonKnjiga.Group;
			this.hbox1.Add(this.radiobuttonIzdanje);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonIzdanje]));
			w4.Position = 3;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radiobuttonAutori = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Autori"));
			this.radiobuttonAutori.CanFocus = true;
			this.radiobuttonAutori.Name = "radiobuttonAutori";
			this.radiobuttonAutori.DrawIndicator = true;
			this.radiobuttonAutori.UseUnderline = true;
			this.radiobuttonAutori.Group = this.radiobuttonKnjiga.Group;
			this.hbox1.Add(this.radiobuttonAutori);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonAutori]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 4;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.widgeturedivanjeknjiga1 = new global::ProjektProgramsko.WidgetUredivanjeKnjiga();
			this.widgeturedivanjeknjiga1.Events = ((global::Gdk.EventMask)(256));
			this.widgeturedivanjeknjiga1.Name = "widgeturedivanjeknjiga1";
			this.vbox2.Add(this.widgeturedivanjeknjiga1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.widgeturedivanjeknjiga1]));
			w7.Position = 0;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w8.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
