
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class GlavniMeni
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.Entry entryPretraga;

		private global::Gtk.Button buttonPretraga;

		private global::Gtk.Button buttonPrijava;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VButtonBox vbuttonbox2;

		private global::Gtk.Button buttonPocetna;

		private global::Gtk.Button buttonKnjige;

		private global::Gtk.Button buttonCasopisi;

		private global::Gtk.Button buttonFilmovi;

		private global::Gtk.Button buttonProfil;

		private global::Gtk.HBox hboxMain;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.GlavniMeni
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ProjektProgramsko.GlavniMeni";
			// Container child ProjektProgramsko.GlavniMeni.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("LogoApp");
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entryPretraga = new global::Gtk.Entry();
			this.entryPretraga.CanFocus = true;
			this.entryPretraga.Name = "entryPretraga";
			this.entryPretraga.IsEditable = true;
			this.entryPretraga.InvisibleChar = '●';
			this.hbox5.Add(this.entryPretraga);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entryPretraga]));
			w2.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.buttonPretraga = new global::Gtk.Button();
			this.buttonPretraga.CanFocus = true;
			this.buttonPretraga.Name = "buttonPretraga";
			this.buttonPretraga.UseUnderline = true;
			this.buttonPretraga.Label = global::Mono.Unix.Catalog.GetString("Pretraži");
			this.hbox5.Add(this.buttonPretraga);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.buttonPretraga]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.buttonPrijava = new global::Gtk.Button();
			this.buttonPrijava.CanFocus = true;
			this.buttonPrijava.Name = "buttonPrijava";
			this.buttonPrijava.UseUnderline = true;
			this.buttonPrijava.Label = global::Mono.Unix.Catalog.GetString("Prijavi se");
			this.hbox5.Add(this.buttonPrijava);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.buttonPrijava]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox4.Add(this.hbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbuttonbox2 = new global::Gtk.VButtonBox();
			this.vbuttonbox2.Name = "vbuttonbox2";
			this.vbuttonbox2.Spacing = -3;
			this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPocetna = new global::Gtk.Button();
			this.buttonPocetna.CanFocus = true;
			this.buttonPocetna.Name = "buttonPocetna";
			this.buttonPocetna.UseUnderline = true;
			this.buttonPocetna.Label = global::Mono.Unix.Catalog.GetString("Početna");
			this.vbuttonbox2.Add(this.buttonPocetna);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonPocetna]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonKnjige = new global::Gtk.Button();
			this.buttonKnjige.CanFocus = true;
			this.buttonKnjige.Name = "buttonKnjige";
			this.buttonKnjige.UseUnderline = true;
			this.buttonKnjige.Label = global::Mono.Unix.Catalog.GetString("Knjige");
			this.vbuttonbox2.Add(this.buttonKnjige);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonKnjige]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCasopisi = new global::Gtk.Button();
			this.buttonCasopisi.CanFocus = true;
			this.buttonCasopisi.Name = "buttonCasopisi";
			this.buttonCasopisi.UseUnderline = true;
			this.buttonCasopisi.Label = global::Mono.Unix.Catalog.GetString("Časopisi");
			this.vbuttonbox2.Add(this.buttonCasopisi);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonCasopisi]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonFilmovi = new global::Gtk.Button();
			this.buttonFilmovi.CanFocus = true;
			this.buttonFilmovi.Name = "buttonFilmovi";
			this.buttonFilmovi.UseUnderline = true;
			this.buttonFilmovi.Label = global::Mono.Unix.Catalog.GetString("Filmovi");
			this.vbuttonbox2.Add(this.buttonFilmovi);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonFilmovi]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonProfil = new global::Gtk.Button();
			this.buttonProfil.CanFocus = true;
			this.buttonProfil.Name = "buttonProfil";
			this.buttonProfil.UseUnderline = true;
			this.buttonProfil.Label = global::Mono.Unix.Catalog.GetString("Profil");
			this.vbuttonbox2.Add(this.buttonProfil);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonProfil]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox1.Add(this.vbuttonbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hboxMain = new global::Gtk.HBox();
			this.hboxMain.Name = "hboxMain";
			this.hboxMain.Spacing = 6;
			this.hbox1.Add(this.hboxMain);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hboxMain]));
			w12.Position = 1;
			this.vbox4.Add(this.hbox1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
			w13.Position = 1;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
