
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class WindowPrijavljivanje
	{
		private global::Gtk.VBox vboxMain;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.WindowPrijavljivanje
			this.Name = "ProjektProgramsko.WindowPrijavljivanje";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowPrijavljivanje");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child ProjektProgramsko.WindowPrijavljivanje.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 373;
			this.DefaultHeight = 313;
			this.Show();
		}
	}
}
