
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class WidgetMojSadrzaj
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.RadioButton radiobuttonKnjiga;

		private global::Gtk.RadioButton radiobuttonFilm;

		private global::Gtk.RadioButton radiobuttonIzdanje;

		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox7;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview1;

		private global::Gtk.HButtonBox hbuttonbox1;

		private global::Gtk.Button buttonPregledaj;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.WidgetMojSadrzaj
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ProjektProgramsko.WidgetMojSadrzaj";
			// Container child ProjektProgramsko.WidgetMojSadrzaj.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radiobuttonKnjiga = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Knjiga"));
			this.radiobuttonKnjiga.CanFocus = true;
			this.radiobuttonKnjiga.Name = "radiobuttonKnjiga";
			this.radiobuttonKnjiga.DrawIndicator = true;
			this.radiobuttonKnjiga.UseUnderline = true;
			this.radiobuttonKnjiga.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox1.Add(this.radiobuttonKnjiga);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonKnjiga]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radiobuttonFilm = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Film"));
			this.radiobuttonFilm.CanFocus = true;
			this.radiobuttonFilm.Name = "radiobuttonFilm";
			this.radiobuttonFilm.DrawIndicator = true;
			this.radiobuttonFilm.UseUnderline = true;
			this.radiobuttonFilm.Group = this.radiobuttonKnjiga.Group;
			this.hbox1.Add(this.radiobuttonFilm);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonFilm]));
			w2.Position = 1;
			w2.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radiobuttonIzdanje = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Izdanje Časopis"));
			this.radiobuttonIzdanje.CanFocus = true;
			this.radiobuttonIzdanje.Name = "radiobuttonIzdanje";
			this.radiobuttonIzdanje.DrawIndicator = true;
			this.radiobuttonIzdanje.UseUnderline = true;
			this.radiobuttonIzdanje.Group = this.radiobuttonKnjiga.Group;
			this.hbox1.Add(this.radiobuttonIzdanje);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonIzdanje]));
			w3.Position = 2;
			w3.Expand = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView();
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add(this.nodeview1);
			this.vbox7.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.GtkScrolledWindow]));
			w6.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPregledaj = new global::Gtk.Button();
			this.buttonPregledaj.CanFocus = true;
			this.buttonPregledaj.Name = "buttonPregledaj";
			this.buttonPregledaj.UseUnderline = true;
			this.buttonPregledaj.Label = global::Mono.Unix.Catalog.GetString("Pregledaj");
			this.hbuttonbox1.Add(this.buttonPregledaj);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.buttonPregledaj]));
			w7.Expand = false;
			w7.Fill = false;
			this.vbox7.Add(this.hbuttonbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbuttonbox1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox2.Add(this.vbox7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox7]));
			w9.Position = 0;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w10.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
