
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class GlavniMeni
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Image image1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Button buttonPrijava;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VButtonBox vbuttonbox2;

		private global::Gtk.Button buttonPocetna;

		private global::Gtk.Button buttonKnjige;

		private global::Gtk.Button buttonCasopisi;

		private global::Gtk.Button buttonFilmovi;

		private global::Gtk.Button buttonProfil;

		private global::Gtk.Button buttonSadrzaj;

		private global::Gtk.Button buttonDodavanje;

		private global::Gtk.Button buttonUredivanje;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vboxMain1;

		private global::Gtk.VBox vboxSort;

		private global::Gtk.ScrolledWindow scrolledwindow3;

		private global::Gtk.VBox vboxMain;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.GlavniMeni
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ProjektProgramsko.GlavniMeni";
			// Container child ProjektProgramsko.GlavniMeni.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.fixed1.Add(this.image1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image1]));
			w1.X = -2;
			w1.Y = 23;
			this.hbox5.Add(this.fixed1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.fixed1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox5.Add(this.fixed2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.fixed2]));
			w3.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.buttonPrijava = new global::Gtk.Button();
			this.buttonPrijava.WidthRequest = 70;
			this.buttonPrijava.HeightRequest = 20;
			this.buttonPrijava.CanFocus = true;
			this.buttonPrijava.Name = "buttonPrijava";
			this.buttonPrijava.UseUnderline = true;
			this.buttonPrijava.Label = global::Mono.Unix.Catalog.GetString("Prijavi se");
			this.hbox5.Add(this.buttonPrijava);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.buttonPrijava]));
			w4.Position = 2;
			w4.Expand = false;
			this.vbox4.Add(this.hbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbuttonbox2 = new global::Gtk.VButtonBox();
			this.vbuttonbox2.Name = "vbuttonbox2";
			this.vbuttonbox2.Spacing = -3;
			this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPocetna = new global::Gtk.Button();
			this.buttonPocetna.WidthRequest = 110;
			this.buttonPocetna.CanFocus = true;
			this.buttonPocetna.Name = "buttonPocetna";
			this.buttonPocetna.UseUnderline = true;
			this.buttonPocetna.Label = global::Mono.Unix.Catalog.GetString("Početna");
			this.vbuttonbox2.Add(this.buttonPocetna);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonPocetna]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonKnjige = new global::Gtk.Button();
			this.buttonKnjige.WidthRequest = 110;
			this.buttonKnjige.CanFocus = true;
			this.buttonKnjige.Name = "buttonKnjige";
			this.buttonKnjige.UseUnderline = true;
			this.buttonKnjige.Label = global::Mono.Unix.Catalog.GetString("Knjige");
			this.vbuttonbox2.Add(this.buttonKnjige);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonKnjige]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCasopisi = new global::Gtk.Button();
			this.buttonCasopisi.WidthRequest = 110;
			this.buttonCasopisi.CanFocus = true;
			this.buttonCasopisi.Name = "buttonCasopisi";
			this.buttonCasopisi.UseUnderline = true;
			this.buttonCasopisi.Label = global::Mono.Unix.Catalog.GetString("Časopisi");
			this.vbuttonbox2.Add(this.buttonCasopisi);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonCasopisi]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonFilmovi = new global::Gtk.Button();
			this.buttonFilmovi.WidthRequest = 110;
			this.buttonFilmovi.CanFocus = true;
			this.buttonFilmovi.Name = "buttonFilmovi";
			this.buttonFilmovi.UseUnderline = true;
			this.buttonFilmovi.Label = global::Mono.Unix.Catalog.GetString("Filmovi");
			this.vbuttonbox2.Add(this.buttonFilmovi);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonFilmovi]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonProfil = new global::Gtk.Button();
			this.buttonProfil.WidthRequest = 110;
			this.buttonProfil.CanFocus = true;
			this.buttonProfil.Name = "buttonProfil";
			this.buttonProfil.UseUnderline = true;
			this.buttonProfil.Label = global::Mono.Unix.Catalog.GetString("Profil");
			this.vbuttonbox2.Add(this.buttonProfil);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonProfil]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonSadrzaj = new global::Gtk.Button();
			this.buttonSadrzaj.CanFocus = true;
			this.buttonSadrzaj.Name = "buttonSadrzaj";
			this.buttonSadrzaj.UseUnderline = true;
			this.buttonSadrzaj.Label = global::Mono.Unix.Catalog.GetString("Moj sadržaj");
			this.vbuttonbox2.Add(this.buttonSadrzaj);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonSadrzaj]));
			w11.Position = 5;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonDodavanje = new global::Gtk.Button();
			this.buttonDodavanje.WidthRequest = 110;
			this.buttonDodavanje.CanFocus = true;
			this.buttonDodavanje.Name = "buttonDodavanje";
			this.buttonDodavanje.UseUnderline = true;
			this.buttonDodavanje.Label = global::Mono.Unix.Catalog.GetString("Dodavanje sadržaja");
			this.vbuttonbox2.Add(this.buttonDodavanje);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonDodavanje]));
			w12.Position = 6;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonUredivanje = new global::Gtk.Button();
			this.buttonUredivanje.WidthRequest = 110;
			this.buttonUredivanje.CanFocus = true;
			this.buttonUredivanje.Name = "buttonUredivanje";
			this.buttonUredivanje.UseUnderline = true;
			this.buttonUredivanje.Label = global::Mono.Unix.Catalog.GetString("Uređivanje sadržaja");
			this.vbuttonbox2.Add(this.buttonUredivanje);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.buttonUredivanje]));
			w13.Position = 7;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox1.Add(this.vbuttonbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox2]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vboxMain1 = new global::Gtk.VBox();
			this.vboxMain1.Name = "vboxMain1";
			this.vboxMain1.Spacing = 6;
			// Container child vboxMain1.Gtk.Box+BoxChild
			this.vboxSort = new global::Gtk.VBox();
			this.vboxSort.Name = "vboxSort";
			this.vboxSort.Spacing = 6;
			this.vboxMain1.Add(this.vboxSort);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxMain1[this.vboxSort]));
			w15.Position = 0;
			w15.Expand = false;
			// Container child vboxMain1.Gtk.Box+BoxChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			global::Gtk.Viewport w16 = new global::Gtk.Viewport();
			w16.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			w16.Add(this.vboxMain);
			this.scrolledwindow3.Add(w16);
			this.vboxMain1.Add(this.scrolledwindow3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxMain1[this.scrolledwindow3]));
			w19.Position = 1;
			w19.Padding = ((uint)(5));
			this.GtkAlignment.Add(this.vboxMain1);
			this.frame2.Add(this.GtkAlignment);
			this.vbox5.Add(this.frame2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.frame2]));
			w22.Position = 0;
			this.hbox1.Add(this.vbox5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox5]));
			w23.Position = 1;
			w23.Padding = ((uint)(5));
			this.vbox4.Add(this.hbox1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
			w24.Position = 1;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.buttonProfil.Hide();
			this.buttonDodavanje.Hide();
			this.buttonUredivanje.Hide();
			this.Hide();
		}
	}
}
