
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class WidgetPayPal
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label6;

		private global::Gtk.Entry entry6;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label7;

		private global::Gtk.Entry entry7;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Button button427;

		private global::Gtk.Button button428;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.WidgetPayPal
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ProjektProgramsko.WidgetPayPal";
			// Container child ProjektProgramsko.WidgetPayPal.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Korisničko ime:");
			this.hbox8.Add(this.label6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entry6 = new global::Gtk.Entry();
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.InvisibleChar = '●';
			this.hbox8.Add(this.entry6);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.entry6]));
			w2.Position = 1;
			this.vbox4.Add(this.hbox8);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox8]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Lozinka");
			this.hbox9.Add(this.label7);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label7]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entry7 = new global::Gtk.Entry();
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.IsEditable = true;
			this.entry7.InvisibleChar = '●';
			this.hbox9.Add(this.entry7);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.entry7]));
			w5.Position = 1;
			this.vbox4.Add(this.hbox9);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox9]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button427 = new global::Gtk.Button();
			this.button427.WidthRequest = 100;
			this.button427.CanFocus = true;
			this.button427.Name = "button427";
			this.button427.UseUnderline = true;
			this.button427.Label = global::Mono.Unix.Catalog.GetString("Potvrdi");
			this.hbox10.Add(this.button427);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.button427]));
			w7.Position = 0;
			w7.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button428 = new global::Gtk.Button();
			this.button428.WidthRequest = 100;
			this.button428.CanFocus = true;
			this.button428.Name = "button428";
			this.button428.UseUnderline = true;
			this.button428.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox10.Add(this.button428);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.button428]));
			w8.Position = 1;
			w8.Fill = false;
			this.vbox4.Add(this.hbox10);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox10]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
