
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class WidgetRegistracija
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.VBox vboxMain;

		private global::Gtk.Entry entryIme;

		private global::Gtk.Entry entryPrezime;

		private global::Gtk.Entry entryKorisnickoIme;

		private global::Gtk.Entry entryEmail;

		private global::Gtk.Entry entryLozinka;

		private global::Gtk.Entry entryPotvrdiLozinku;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.HButtonBox hbuttonbox2;

		private global::Gtk.Button buttonPotvrdi;

		private global::Gtk.Button buttonNatrag;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.WidgetRegistracija
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ProjektProgramsko.WidgetRegistracija";
			// Container child ProjektProgramsko.WidgetRegistracija.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Ime:");
			this.vbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w1.Position = 0;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Prezime:");
			this.vbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label2]));
			w2.Position = 1;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Korisničko ime:");
			this.vbox2.Add(this.label3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label3]));
			w3.Position = 2;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("e-mail");
			this.vbox2.Add(this.label4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
			w4.Position = 3;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Lozinka");
			this.vbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label5]));
			w5.Position = 4;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Potvrdi Lozinku");
			this.vbox2.Add(this.label6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label6]));
			w6.Position = 5;
			w6.Fill = false;
			this.hbox2.Add(this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.entryIme = new global::Gtk.Entry();
			this.entryIme.CanFocus = true;
			this.entryIme.Name = "entryIme";
			this.entryIme.IsEditable = true;
			this.entryIme.InvisibleChar = '●';
			this.vboxMain.Add(this.entryIme);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.entryIme]));
			w8.Position = 0;
			w8.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.entryPrezime = new global::Gtk.Entry();
			this.entryPrezime.CanFocus = true;
			this.entryPrezime.Name = "entryPrezime";
			this.entryPrezime.IsEditable = true;
			this.entryPrezime.InvisibleChar = '●';
			this.vboxMain.Add(this.entryPrezime);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.entryPrezime]));
			w9.Position = 1;
			w9.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.entryKorisnickoIme = new global::Gtk.Entry();
			this.entryKorisnickoIme.CanFocus = true;
			this.entryKorisnickoIme.Name = "entryKorisnickoIme";
			this.entryKorisnickoIme.IsEditable = true;
			this.entryKorisnickoIme.InvisibleChar = '●';
			this.vboxMain.Add(this.entryKorisnickoIme);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.entryKorisnickoIme]));
			w10.Position = 2;
			w10.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.entryEmail = new global::Gtk.Entry();
			this.entryEmail.CanFocus = true;
			this.entryEmail.Name = "entryEmail";
			this.entryEmail.IsEditable = true;
			this.entryEmail.InvisibleChar = '●';
			this.vboxMain.Add(this.entryEmail);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.entryEmail]));
			w11.Position = 3;
			w11.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.entryLozinka = new global::Gtk.Entry();
			this.entryLozinka.CanFocus = true;
			this.entryLozinka.Name = "entryLozinka";
			this.entryLozinka.IsEditable = true;
			this.entryLozinka.Visibility = false;
			this.entryLozinka.InvisibleChar = '●';
			this.vboxMain.Add(this.entryLozinka);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.entryLozinka]));
			w12.Position = 4;
			w12.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.entryPotvrdiLozinku = new global::Gtk.Entry();
			this.entryPotvrdiLozinku.CanFocus = true;
			this.entryPotvrdiLozinku.Name = "entryPotvrdiLozinku";
			this.entryPotvrdiLozinku.IsEditable = true;
			this.entryPotvrdiLozinku.Visibility = false;
			this.entryPotvrdiLozinku.InvisibleChar = '●';
			this.vboxMain.Add(this.entryPotvrdiLozinku);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.entryPotvrdiLozinku]));
			w13.Position = 5;
			w13.Fill = false;
			this.hbox2.Add(this.vboxMain);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vboxMain]));
			w14.Position = 1;
			this.vbox3.Add(this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox3.Add(this.fixed1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.fixed1]));
			w16.Position = 1;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPotvrdi = new global::Gtk.Button();
			this.buttonPotvrdi.CanFocus = true;
			this.buttonPotvrdi.Name = "buttonPotvrdi";
			this.buttonPotvrdi.UseUnderline = true;
			this.buttonPotvrdi.Label = global::Mono.Unix.Catalog.GetString("Potvrdi");
			this.hbuttonbox2.Add(this.buttonPotvrdi);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.buttonPotvrdi]));
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonNatrag = new global::Gtk.Button();
			this.buttonNatrag.CanFocus = true;
			this.buttonNatrag.Name = "buttonNatrag";
			this.buttonNatrag.UseUnderline = true;
			this.buttonNatrag.Label = global::Mono.Unix.Catalog.GetString("Natrag");
			this.hbuttonbox2.Add(this.buttonNatrag);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.buttonNatrag]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox3.Add(this.hbuttonbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbuttonbox2]));
			w19.Position = 0;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.hbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w21.PackType = ((global::Gtk.PackType)(1));
			w21.Position = 0;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
