
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class GlavniMeni
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.Entry entry3;

		private global::Gtk.Button button63;

		private global::Gtk.Button button64;

		private global::Gtk.HBox hboxMain;

		private global::Gtk.VButtonBox vbuttonbox2;

		private global::Gtk.Button button65;

		private global::Gtk.Button button66;

		private global::Gtk.Button button67;

		private global::Gtk.Button button68;

		private global::Gtk.Button button69;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.GlavniMeni
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ProjektProgramsko.GlavniMeni";
			// Container child ProjektProgramsko.GlavniMeni.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("LogoApp");
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.hbox5.Add(this.entry3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry3]));
			w2.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.button63 = new global::Gtk.Button();
			this.button63.CanFocus = true;
			this.button63.Name = "button63";
			this.button63.UseUnderline = true;
			this.button63.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.hbox5.Add(this.button63);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button63]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.button64 = new global::Gtk.Button();
			this.button64.CanFocus = true;
			this.button64.Name = "button64";
			this.button64.UseUnderline = true;
			this.button64.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.hbox5.Add(this.button64);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button64]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox4.Add(this.hbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hboxMain = new global::Gtk.HBox();
			this.hboxMain.Name = "hboxMain";
			this.hboxMain.Spacing = 6;
			// Container child hboxMain.Gtk.Box+BoxChild
			this.vbuttonbox2 = new global::Gtk.VButtonBox();
			this.vbuttonbox2.Name = "vbuttonbox2";
			this.vbuttonbox2.Spacing = -3;
			this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button65 = new global::Gtk.Button();
			this.button65.CanFocus = true;
			this.button65.Name = "button65";
			this.button65.UseUnderline = true;
			this.button65.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.vbuttonbox2.Add(this.button65);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.button65]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button66 = new global::Gtk.Button();
			this.button66.CanFocus = true;
			this.button66.Name = "button66";
			this.button66.UseUnderline = true;
			this.button66.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.vbuttonbox2.Add(this.button66);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.button66]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button67 = new global::Gtk.Button();
			this.button67.CanFocus = true;
			this.button67.Name = "button67";
			this.button67.UseUnderline = true;
			this.button67.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.vbuttonbox2.Add(this.button67);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.button67]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button68 = new global::Gtk.Button();
			this.button68.CanFocus = true;
			this.button68.Name = "button68";
			this.button68.UseUnderline = true;
			this.button68.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.vbuttonbox2.Add(this.button68);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.button68]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button69 = new global::Gtk.Button();
			this.button69.CanFocus = true;
			this.button69.Name = "button69";
			this.button69.UseUnderline = true;
			this.button69.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.vbuttonbox2.Add(this.button69);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.button69]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			this.hboxMain.Add(this.vbuttonbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxMain[this.vbuttonbox2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox4.Add(this.hboxMain);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hboxMain]));
			w12.Position = 1;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
