
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class WindowRegistracija
	{
		private global::Gtk.HBox hbox11;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Image image1;

		private global::Gtk.FileChooserButton filechooserbutton1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label6;

		private global::Gtk.Entry entryregistacijaime;

		private global::Gtk.Label label7;

		private global::Gtk.Entry entryregistracijaprezime;

		private global::Gtk.Label label8;

		private global::Gtk.Entry entryregistracijakorisnickoime;

		private global::Gtk.Label label9;

		private global::Gtk.Entry entryregistracijaemail;

		private global::Gtk.Label label10;

		private global::Gtk.Entry entryregistracijalozinka;

		private global::Gtk.Label label11;

		private global::Gtk.Entry entryregistracijapotvrdilozinku;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Button buttonspremi;

		private global::Gtk.Button buttonodustani;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.WindowRegistracija
			this.Name = "ProjektProgramsko.WindowRegistracija";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowRegistracija");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProjektProgramsko.WindowRegistracija.Gtk.Container+ContainerChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image();
			this.image1.WidthRequest = 150;
			this.image1.HeightRequest = 150;
			this.image1.Name = "image1";
			this.vbox2.Add(this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.filechooserbutton1 = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.filechooserbutton1.Name = "filechooserbutton1";
			this.vbox2.Add(this.filechooserbutton1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.filechooserbutton1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox11.Add(this.vbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Ime");
			this.vbox3.Add(this.label6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label6]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.entryregistacijaime = new global::Gtk.Entry();
			this.entryregistacijaime.CanFocus = true;
			this.entryregistacijaime.Name = "entryregistacijaime";
			this.entryregistacijaime.IsEditable = true;
			this.entryregistacijaime.InvisibleChar = '●';
			this.vbox3.Add(this.entryregistacijaime);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.entryregistacijaime]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Prezime");
			this.vbox3.Add(this.label7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label7]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.entryregistracijaprezime = new global::Gtk.Entry();
			this.entryregistracijaprezime.CanFocus = true;
			this.entryregistracijaprezime.Name = "entryregistracijaprezime";
			this.entryregistracijaprezime.IsEditable = true;
			this.entryregistracijaprezime.InvisibleChar = '●';
			this.vbox3.Add(this.entryregistracijaprezime);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.entryregistracijaprezime]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Korisničko ime");
			this.vbox3.Add(this.label8);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label8]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.entryregistracijakorisnickoime = new global::Gtk.Entry();
			this.entryregistracijakorisnickoime.CanFocus = true;
			this.entryregistracijakorisnickoime.Name = "entryregistracijakorisnickoime";
			this.entryregistracijakorisnickoime.IsEditable = true;
			this.entryregistracijakorisnickoime.InvisibleChar = '●';
			this.vbox3.Add(this.entryregistracijakorisnickoime);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.entryregistracijakorisnickoime]));
			w9.Position = 5;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("e-mail");
			this.vbox3.Add(this.label9);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label9]));
			w10.Position = 6;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.entryregistracijaemail = new global::Gtk.Entry();
			this.entryregistracijaemail.CanFocus = true;
			this.entryregistracijaemail.Name = "entryregistracijaemail";
			this.entryregistracijaemail.IsEditable = true;
			this.entryregistracijaemail.InvisibleChar = '●';
			this.vbox3.Add(this.entryregistracijaemail);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.entryregistracijaemail]));
			w11.Position = 7;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Lozinka");
			this.vbox3.Add(this.label10);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label10]));
			w12.Position = 8;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.entryregistracijalozinka = new global::Gtk.Entry();
			this.entryregistracijalozinka.CanFocus = true;
			this.entryregistracijalozinka.Name = "entryregistracijalozinka";
			this.entryregistracijalozinka.IsEditable = true;
			this.entryregistracijalozinka.InvisibleChar = '●';
			this.vbox3.Add(this.entryregistracijalozinka);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.entryregistracijalozinka]));
			w13.Position = 9;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Potvrdi Lozinku");
			this.vbox3.Add(this.label11);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label11]));
			w14.Position = 10;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.entryregistracijapotvrdilozinku = new global::Gtk.Entry();
			this.entryregistracijapotvrdilozinku.CanFocus = true;
			this.entryregistracijapotvrdilozinku.Name = "entryregistracijapotvrdilozinku";
			this.entryregistracijapotvrdilozinku.IsEditable = true;
			this.entryregistracijapotvrdilozinku.InvisibleChar = '●';
			this.vbox3.Add(this.entryregistracijapotvrdilozinku);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.entryregistracijapotvrdilozinku]));
			w15.Position = 11;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.buttonspremi = new global::Gtk.Button();
			this.buttonspremi.WidthRequest = 100;
			this.buttonspremi.CanFocus = true;
			this.buttonspremi.Name = "buttonspremi";
			this.buttonspremi.UseUnderline = true;
			this.buttonspremi.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			this.hbox12.Add(this.buttonspremi);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.buttonspremi]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.buttonodustani = new global::Gtk.Button();
			this.buttonodustani.WidthRequest = 100;
			this.buttonodustani.CanFocus = true;
			this.buttonodustani.Name = "buttonodustani";
			this.buttonodustani.UseUnderline = true;
			this.buttonodustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox12.Add(this.buttonodustani);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.buttonodustani]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox3.Add(this.hbox12);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox12]));
			w18.Position = 12;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox11.Add(this.vbox3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vbox3]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.Add(this.hbox11);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 410;
			this.DefaultHeight = 394;
			this.Show();
		}
	}
}
