
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class WidgetSortFilmovi
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBox comboboxSort;

		private global::Gtk.ComboBox comboboxTag;

		private global::Gtk.Label label4;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Entry entry3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.WidgetSortFilmovi
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ProjektProgramsko.WidgetSortFilmovi";
			// Container child ProjektProgramsko.WidgetSortFilmovi.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Sortiraj po:");
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboboxSort = global::Gtk.ComboBox.NewText();
			this.comboboxSort.AppendText(global::Mono.Unix.Catalog.GetString("Abeceda (uzlazno)"));
			this.comboboxSort.AppendText(global::Mono.Unix.Catalog.GetString("Abeceda (silazno)"));
			this.comboboxSort.AppendText(global::Mono.Unix.Catalog.GetString("Cijena (uzlazno)"));
			this.comboboxSort.AppendText(global::Mono.Unix.Catalog.GetString("Cijena (silazno)"));
			this.comboboxSort.AppendText(global::Mono.Unix.Catalog.GetString("Najprodavanije"));
			this.comboboxSort.AppendText(global::Mono.Unix.Catalog.GetString("Najnovije"));
			this.comboboxSort.Name = "comboboxSort";
			this.hbox5.Add(this.comboboxSort);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.comboboxSort]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboboxTag = global::Gtk.ComboBox.NewText();
			this.comboboxTag.AppendText(global::Mono.Unix.Catalog.GetString("Znanost"));
			this.comboboxTag.AppendText(global::Mono.Unix.Catalog.GetString("Povijest"));
			this.comboboxTag.AppendText(global::Mono.Unix.Catalog.GetString("Biografija"));
			this.comboboxTag.AppendText(global::Mono.Unix.Catalog.GetString("Priroda"));
			this.comboboxTag.Name = "comboboxTag";
			this.hbox5.Add(this.comboboxTag);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.comboboxTag]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Tagovi:");
			this.hbox5.Add(this.label4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label4]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox3.Add(this.hbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.hbox3.Add(this.entry3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry3]));
			w6.Position = 0;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
