
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class WindowPrijava
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.Entry entry2;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label2;

		private global::Gtk.Entry entry1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button buttonPrijavaPotvrdi;

		private global::Gtk.Button buttonPrijavaOdustani;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label3;

		private global::Gtk.Button buttonPrijavaRegistrirajse;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.WindowPrijava
			this.WidthRequest = 250;
			this.HeightRequest = 150;
			this.Name = "ProjektProgramsko.WindowPrijava";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowPrijava");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProjektProgramsko.WindowPrijava.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(3));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Korisničko Ime");
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.hbox1.Add(this.entry2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry2]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 1;
			w2.Expand = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Lozinka");
			this.hbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.hbox2.Add(this.entry1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entry1]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 1;
			w5.Expand = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonPrijavaPotvrdi = new global::Gtk.Button();
			this.buttonPrijavaPotvrdi.WidthRequest = 100;
			this.buttonPrijavaPotvrdi.CanFocus = true;
			this.buttonPrijavaPotvrdi.Name = "buttonPrijavaPotvrdi";
			this.buttonPrijavaPotvrdi.UseUnderline = true;
			this.buttonPrijavaPotvrdi.Label = global::Mono.Unix.Catalog.GetString("Potvrdi");
			this.hbox3.Add(this.buttonPrijavaPotvrdi);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonPrijavaPotvrdi]));
			w7.Position = 0;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonPrijavaOdustani = new global::Gtk.Button();
			this.buttonPrijavaOdustani.WidthRequest = 100;
			this.buttonPrijavaOdustani.CanFocus = true;
			this.buttonPrijavaOdustani.Name = "buttonPrijavaOdustani";
			this.buttonPrijavaOdustani.UseUnderline = true;
			this.buttonPrijavaOdustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox3.Add(this.buttonPrijavaOdustani);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonPrijavaOdustani]));
			w8.Position = 1;
			w8.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Nemaš korisnički račun?");
			this.hbox4.Add(this.label3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label3]));
			w10.Position = 0;
			w10.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonPrijavaRegistrirajse = new global::Gtk.Button();
			this.buttonPrijavaRegistrirajse.CanFocus = true;
			this.buttonPrijavaRegistrirajse.Name = "buttonPrijavaRegistrirajse";
			this.buttonPrijavaRegistrirajse.UseUnderline = true;
			this.buttonPrijavaRegistrirajse.Label = global::Mono.Unix.Catalog.GetString("Registriraj se");
			this.hbox4.Add(this.buttonPrijavaRegistrirajse);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonPrijavaRegistrirajse]));
			w11.Position = 1;
			w11.Fill = false;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 296;
			this.DefaultHeight = 174;
			this.Show();
		}
	}
}
