
// This file has been generated by the GUI designer. Do not modify.
namespace ProjektProgramsko
{
	public partial class WindowPrijava
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label label12;

		private global::Gtk.Entry entryprij;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Label entry;

		private global::Gtk.Entry entry10;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Button buttonPotvrdi;

		private global::Gtk.Button buttonOdustani;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Label label14;

		private global::Gtk.Button buttonRegistrirajse;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProjektProgramsko.WindowPrijava
			this.Name = "ProjektProgramsko.WindowPrijava";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowPrijava");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(5));
			this.AllowGrow = false;
			this.DefaultWidth = 150;
			this.DefaultHeight = 50;
			// Container child ProjektProgramsko.WindowPrijava.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(4));
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Korisničko ime");
			this.hbox13.Add(this.label12);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label12]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.entryprij = new global::Gtk.Entry();
			this.entryprij.WidthRequest = 200;
			this.entryprij.CanFocus = true;
			this.entryprij.Name = "entryprij";
			this.entryprij.IsEditable = true;
			this.entryprij.InvisibleChar = '●';
			this.hbox13.Add(this.entryprij);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.entryprij]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 1;
			w2.Expand = false;
			this.vbox4.Add(this.hbox13);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox13]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.entry = new global::Gtk.Label();
			this.entry.Name = "entry";
			this.entry.LabelProp = global::Mono.Unix.Catalog.GetString("Lozinka");
			this.hbox14.Add(this.entry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.entry]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.entry10 = new global::Gtk.Entry();
			this.entry10.WidthRequest = 200;
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '●';
			this.hbox14.Add(this.entry10);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.entry10]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 1;
			w5.Expand = false;
			this.vbox4.Add(this.hbox14);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox14]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.buttonPotvrdi = new global::Gtk.Button();
			this.buttonPotvrdi.CanFocus = true;
			this.buttonPotvrdi.Name = "buttonPotvrdi";
			this.buttonPotvrdi.UseUnderline = true;
			this.buttonPotvrdi.Label = global::Mono.Unix.Catalog.GetString("Potvrdi");
			this.hbox15.Add(this.buttonPotvrdi);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.buttonPotvrdi]));
			w7.Position = 0;
			w7.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.buttonOdustani = new global::Gtk.Button();
			this.buttonOdustani.CanFocus = true;
			this.buttonOdustani.Name = "buttonOdustani";
			this.buttonOdustani.UseUnderline = true;
			this.buttonOdustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox15.Add(this.buttonOdustani);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.buttonOdustani]));
			w8.Position = 1;
			w8.Fill = false;
			this.vbox4.Add(this.hbox15);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox15]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.Xalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Nemaš korisnički račun?");
			this.hbox16.Add(this.label14);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label14]));
			w10.Position = 0;
			w10.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.buttonRegistrirajse = new global::Gtk.Button();
			this.buttonRegistrirajse.CanFocus = true;
			this.buttonRegistrirajse.Name = "buttonRegistrirajse";
			this.buttonRegistrirajse.UseUnderline = true;
			this.buttonRegistrirajse.Label = global::Mono.Unix.Catalog.GetString("Registriraj se");
			this.hbox16.Add(this.buttonRegistrirajse);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.buttonRegistrirajse]));
			w11.Position = 1;
			w11.Fill = false;
			this.vbox4.Add(this.hbox16);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox16]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
		}
	}
}
